name: Calculator CD

on:
  workflow_run:
    workflows: ["Calculator CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/calculator-api:latest

    - name: Run container
      run: |
        docker rm -f calculator || true
        docker run -d -p 3000:3000 --name calculator \
        ${{ secrets.DOCKERHUB_USERNAME }}/calculator-api:latest

    - name: Health check
      run: |
        sleep 5
        curl -f http://localhost:3000/health
